<?php
return  array(
    'columns'=> array(
        'item_id' => array(
            'type' => 'table:item',
            'required' => true,
            //'pkey' => true,
            'label' => app::get('sysitem')->_('商品名称'),
            'comment' => app::get('sysitem')->_('商品 ID'),
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' => 11,
        ),
        'shop_id' => array(
            'type' => 'table:shop@sysshop',
            'required' => true,
            'label' => app::get('sysitem')->_('所属店铺'),
            'comment' => app::get('sysitem')->_('店铺id'),
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' => 11,
        ),
        'approve_status' => array(
            'type' => array(
                'onsale' => app::get('sysitem')->_('出售中'),
                'instock' => app::get('sysitem')->_('库中'),
                'check' => app::get('sysitem')->_('审核中'),
            ),
            'required' => true,
            'default' => 'instock',
            'label' => app::get('sysitem')->_('商品状态'),
            'comment' => app::get('sysitem')->_('商品状态'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order'=>19,
        ),
        'check_res' => array(
            'type' => array(
                'active' => app::get('sysitem')->_('未审核'),
                'successful' => app::get('sysitem')->_('已通过'),
                'failing' => app::get('sysitem')->_('拒绝'),
            ),
            'required' => true,
            'default' => 'active',
            //'pkey' => true,
            'label' => app::get('sysitem')->_('审核结果'),
            'comment' => app::get('sysitem')->_('审核结果'),
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order'=>19,
        ),
        'shenhe_num' => array(
            'type' => 'number',
            'required' => true,
            'default' => 0,
            'label' => app::get('sysitem')->_('审核次数'),
            'comment' => app::get('sysitem')->_('审核次数'),
            'in_list' => true,
            'default_in_list' => true,
            'searchtype' => 'has',
            'filtertype' => 'yes',
            'filterdefault' => true,
        ),
        'is_Adjusted' => array(
            'type' => 'bool',
            'default' => 0,
            'label' => app::get('sysitem')->_('是否是调整后价格'),
            'comment' => app::get('sysitem')->_('是否是调整后价格'),
            // 'in_list' => true,
            'default_in_list' => true,
        ),
        'comment' => array(
            'type' => 'text',
            'comment' => app::get('sysitem')->_('备注'),
        ),
        'list_time' => array(
            'type' => 'time',
            'label' => app::get('sysitem')->_('上架时间'),
            'comment' => app::get('sysitem')->_('上架时间'),
            'in_list' => true,
            'default_in_list' => true,
            'order'=>20,
        ),
        'delist_time' => array(
            'type' => 'time',
            'label' => app::get('sysitem')->_('下架时间'),
            'comment' => app::get('sysitem')->_('下架时间'),
            'in_list' => true,
            'default_in_list' => true,
            'order'=>21,
        ),
    ),
    
    'primary' => 'item_id',
    'comment' => app::get('sysitem')->_('商品上下架状态表'),
);
